import sqlite3

from . import dbfunctions

dbfunctions.dbsetup()

con = sqlite3.connect(dbfunctions.DB_FILE)
con.execute("CREATE TABLE expressions(id INTEGER PRIMARY KEY, text char(120) NOT NULL)")
con.execute("INSERT INTO expressions (text) VALUES ('A glittering gem is not enough.')")
con.execute("INSERT INTO expressions (text) VALUES ('A purple pig and a green donkey flew a kite in the middle of the night and ended up sunburnt.')")
con.execute("INSERT INTO expressions (text) VALUES ('A song can make or ruin a person’s day if they let it get to them.')")
con.execute("INSERT INTO expressions (text) VALUES ('Abstraction is often one floor above you.')")
con.execute("INSERT INTO expressions (text) VALUES ('Cats are good pets, for they are clean and are not noisy.')")
con.execute("INSERT INTO expressions (text) VALUES ('Check back tomorrow; I will see if the book has arrived.')")
con.execute("INSERT INTO expressions (text) VALUES ('Christmas is coming.')")
con.execute("INSERT INTO expressions (text) VALUES ('Don't step on the broken glass.')")
con.execute("INSERT INTO expressions (text) VALUES ('Don\\'t step on the broken glass.')")
con.execute("INSERT INTO expressions (text) VALUES ('Everyone was busy, so I went to the movie alone.')")
con.execute("INSERT INTO expressions (text) VALUES ('He didn’t want to go to the dentist, yet he went anyway.')")
con.execute("INSERT INTO expressions (text) VALUES ('He ran out of money, so he had to stop playing poker.')")
con.execute("INSERT INTO expressions (text) VALUES ('He said he was not there yesterday; however, many people saw him there.')")
con.execute("INSERT INTO expressions (text) VALUES ('He told us a very exciting adventure story.')")
con.execute("INSERT INTO expressions (text) VALUES ('He turned in the research paper on Friday; otherwise, he would have not passed the class.')")
con.execute("INSERT INTO expressions (text) VALUES ('How was the math test?')")
con.execute("INSERT INTO expressions (text) VALUES ('Hurry!')")
con.execute("INSERT INTO expressions (text) VALUES ('I am counting my calories, yet I really want dessert.')")
con.execute("INSERT INTO expressions (text) VALUES ('I am happy to take your donation; any amount will be greatly appreciated.')")
con.execute("INSERT INTO expressions (text) VALUES ('I am never at home on Sundays.')")
con.execute("INSERT INTO expressions (text) VALUES ('I checked to make sure that he was still alive.')")
con.execute("INSERT INTO expressions (text) VALUES ('I currently have 4 windows open up… and I don’t know why.')")
con.execute("INSERT INTO expressions (text) VALUES ('I hear that Nancy is very pretty.')")
con.execute("INSERT INTO expressions (text) VALUES ('I love eating toasted cheese and tuna sandwiches.')")
con.execute("INSERT INTO expressions (text) VALUES ('I often see the time 11:11 or 12:34 on clocks.')")
con.execute("INSERT INTO expressions (text) VALUES ('I really want to go to work, but I am too sick to drive.')")
con.execute("INSERT INTO expressions (text) VALUES ('I think I will buy the red car, or I will lease the blue one.')")
con.execute("INSERT INTO expressions (text) VALUES ('I want more detailed information.')")
con.execute("INSERT INTO expressions (text) VALUES ('I want to buy a onesie… but know it won\\’t suit me.')")
con.execute("INSERT INTO expressions (text) VALUES ('I was very proud of my nickname throughout high school but today- I couldn’t be any different to what my nickname was.')")
con.execute("INSERT INTO expressions (text) VALUES ('I will never be this young again. Ever. Oh damn… I just got older.')")
con.execute("INSERT INTO expressions (text) VALUES ('I would have gotten the promotion, but my attendance wasn’t good enough.')")
con.execute("INSERT INTO expressions (text) VALUES ('I'd rather be a bird than a fish.')")
con.execute("INSERT INTO expressions (text) VALUES ('I\\'d rather be a bird than a fish.')")
con.execute("INSERT INTO expressions (text) VALUES ('If I don’t like something, I’ll stay away from it.')")
con.execute("INSERT INTO expressions (text) VALUES ('If Purple People Eaters are real… where do they find purple people to eat?')")
con.execute("INSERT INTO expressions (text) VALUES ('If the Easter Bunny and the Tooth Fairy had babies would they take your teeth and leave chocolate for you?')")
con.execute("INSERT INTO expressions (text) VALUES ('If you like tuna and tomato sauce- try combining the two. It’s really not as bad as it sounds.')")
con.execute("INSERT INTO expressions (text) VALUES ('Is it free?')")
con.execute("INSERT INTO expressions (text) VALUES ('It was getting dark, and we weren’t there yet.')")
con.execute("INSERT INTO expressions (text) VALUES ('Italy is my favorite country; in fact, I plan to spend two weeks there next year.')")
con.execute("INSERT INTO expressions (text) VALUES ('Joe made the sugar cookies; Susan decorated them.')")
con.execute("INSERT INTO expressions (text) VALUES ('Last Friday in three week’s time I saw a spotted striped blue worm shake hands with a legless lizard.')")
con.execute("INSERT INTO expressions (text) VALUES ('Let me help you with your baggage.')")
con.execute("INSERT INTO expressions (text) VALUES ('Lets all be unique together until we realise we are all the same.')")
con.execute("INSERT INTO expressions (text) VALUES ('Malls are great places to shop; I can find everything I need under one roof.')")
con.execute("INSERT INTO expressions (text) VALUES ('Mary plays the piano.')")
con.execute("INSERT INTO expressions (text) VALUES ('My Mum tries to be cool by saying that she likes all the same things that I do.')")
con.execute("INSERT INTO expressions (text) VALUES ('Please wait outside of the house.')")
con.execute("INSERT INTO expressions (text) VALUES ('Rock music approaches at high velocity.')")
con.execute("INSERT INTO expressions (text) VALUES ('She advised him to come back at once.')")
con.execute("INSERT INTO expressions (text) VALUES ('She always speaks to him in a loud voice.')")
con.execute("INSERT INTO expressions (text) VALUES ('She borrowed the book from him many years ago and hasn\'t yet returned it.')")
con.execute("INSERT INTO expressions (text) VALUES ('She borrowed the book from him many years ago and hasn\\'t yet returned it.')")
con.execute("INSERT INTO expressions (text) VALUES ('She did her best to help him.')")
con.execute("INSERT INTO expressions (text) VALUES ('She did not cheat on the test, for it was not the right thing to do.')")
con.execute("INSERT INTO expressions (text) VALUES ('She folded her handkerchief neatly.')")
con.execute("INSERT INTO expressions (text) VALUES ('She only paints with bold colors; she does not like pastels.')")
con.execute("INSERT INTO expressions (text) VALUES ('She was too short to see over the fence.')")
con.execute("INSERT INTO expressions (text) VALUES ('She works two jobs to make ends meet; at least, that was her reason for not having time to join us.')")
con.execute("INSERT INTO expressions (text) VALUES ('She wrote him a long letter, but he didn\\'t read it.')")
con.execute("INSERT INTO expressions (text) VALUES ('Should we start class now, or should we wait for everyone to get here?')")
con.execute("INSERT INTO expressions (text) VALUES ('Sixty-Four comes asking for bread.')")
con.execute("INSERT INTO expressions (text) VALUES ('Someone I know recently combined Maple Syrup & buttered Popcorn thinking it would taste like caramel popcorn. It didn’t and they don’t recommend anyone else do it either.')")
con.execute("INSERT INTO expressions (text) VALUES ('Sometimes it is better to just walk away from things and go back to them later when you’re in a better frame of mind.')")
con.execute("INSERT INTO expressions (text) VALUES ('Sometimes, all you need to do is completely make an ass of yourself and laugh it off to realise that life isn’t so bad after all.')")
con.execute("INSERT INTO expressions (text) VALUES ('The body may perhaps compensates for the loss of a true metaphysics.')")
con.execute("INSERT INTO expressions (text) VALUES ('The book is in front of the table.')")
con.execute("INSERT INTO expressions (text) VALUES ('The clock within this blog and the clock on my laptop are 1 hour different from each other.')")
con.execute("INSERT INTO expressions (text) VALUES ('The lake is a long way from here.')")
con.execute("INSERT INTO expressions (text) VALUES ('The memory we used to share is no longer coherent.')")
con.execute("INSERT INTO expressions (text) VALUES ('The mysterious diary records the voice.')")
con.execute("INSERT INTO expressions (text) VALUES ('The old apple revels in its authority.')")
con.execute("INSERT INTO expressions (text) VALUES ('The quick brown fox jumps over the lazy dog.')")
con.execute("INSERT INTO expressions (text) VALUES ('The river stole the gods.')")
con.execute("INSERT INTO expressions (text) VALUES ('The shooter says goodbye to his love.')")
con.execute("INSERT INTO expressions (text) VALUES ('The sky is clear; the stars are twinkling.')")
con.execute("INSERT INTO expressions (text) VALUES ('The stranger officiates the meal.')")
con.execute("INSERT INTO expressions (text) VALUES ('The waves were crashing on the shore; it was a lovely sight.')")
con.execute("INSERT INTO expressions (text) VALUES ('There was no ice cream in the freezer, nor did they have money to go to the store.')")
con.execute("INSERT INTO expressions (text) VALUES ('There were white out conditions in the town; subsequently, the roads were impassable.')")
con.execute("INSERT INTO expressions (text) VALUES ('They got there early, and they got really good seats.')")
con.execute("INSERT INTO expressions (text) VALUES ('This is a Japanese doll.')")
con.execute("INSERT INTO expressions (text) VALUES ('This is the last random sentence I will be writing and I am going to stop mid-sent')")
con.execute("INSERT INTO expressions (text) VALUES ('Tom got a small piece of pie.')")
con.execute("INSERT INTO expressions (text) VALUES ('Two seats were vacant.')")
con.execute("INSERT INTO expressions (text) VALUES ('We have a lot of rain in June.')")
con.execute("INSERT INTO expressions (text) VALUES ('We have never been to Asia, nor have we visited Africa.')")
con.execute("INSERT INTO expressions (text) VALUES ('We need to rent a room for our party.')")
con.execute("INSERT INTO expressions (text) VALUES ('Wednesday is hump day, but has anyone asked the camel if he’s happy about it?')")
con.execute("INSERT INTO expressions (text) VALUES ('What was the person thinking when they discovered cow’s milk was fine for human consumption… and why did they do it in the first place!?')")
con.execute("INSERT INTO expressions (text) VALUES ('When I was little I had a car door slammed shut on my hand. I still remember it quite vividly.')")
con.execute("INSERT INTO expressions (text) VALUES ('Where do random thoughts come from?')")
con.execute("INSERT INTO expressions (text) VALUES ('Wow, does that work?')")
con.execute("INSERT INTO expressions (text) VALUES ('Writing a list of random sentences is harder than I initially thought it would be.')")
con.execute("INSERT INTO expressions (text) VALUES ('Yeah, I think it\\'s a good environment for learning English.')")
